spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:itmo_market}
    username: ${DB_USER:itmo_user}
    password: ${DB_PASSWORD:itmo_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  flyway:
    locations: classpath:db/migration
    schemas: order_service

server:
  port: ${SERVER_PORT:8083}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}

logging:
  level:
    ru.itmo.order: INFO
